---
name:             InventoryMonitor
main:             presentkim\inventorymonitor\InventoryMonitor
version:          1.0.3
api:              [3.0.0-ALPHA11]
author:           PresentKim
website:          https://github.com/PMMPPlugin/InventoryMonitor
description:      A plugin show other player's inventory

permissions:
  inventorymonitor.cmd:
    description:  InventoryMonitor main command
    default:      op
    children:
      inventorymonitor.cmd.view:
        description:  InventoryMonitor command - view
        default:      op
      inventorymonitor.cmd.lang:
        description:  InventoryMonitor command - lang
        default:      op
      inventorymonitor.cmd.reload:
        description:  InventoryMonitor command - reload
        default:      op
...
